#!/usr/bin/env bash

function main() {
    parseParametersToSetState $@

    if [[ $state == "start" ]]; then        
        qemu-system-aarch64 \
            -M raspi2 \
            -m 1G \
            -no-reboot \
            -nographic \
            -monitor telnet:127.0.0.1:1234,server,nowait \
            -kernel first.bin
    fi
}

function parseParametersToSetState() {
    [[ $# == 0 ]] && error "Needs a command."
    
    while true; do
        case "$1" in
            start) state="start"; shift 1; break;;
            *) error "Not a valid command."
        esac
    done
}

function error() {
    echo "ERROR: $1"
    exit 1
}

main $@
